// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	users "movies/definitions/users"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// GetAuthUser provides a mock function with given fields:
func (_m *AuthService) GetAuthUser() users.User {
	ret := _m.Called()

	var r0 users.User
	if rf, ok := ret.Get(0).(func() users.User); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(users.User)
	}

	return r0
}

type mockConstructorTestingTNewAuthService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthService(t mockConstructorTestingTNewAuthService) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
