// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	movies "movies/definitions/movies"

	mock "github.com/stretchr/testify/mock"
)

// TMDBClient is an autogenerated mock type for the TMDBClient type
type TMDBClient struct {
	mock.Mock
}

// SearchTMDBByNameAndYear provides a mock function with given fields: req
func (_m *TMDBClient) SearchTMDBByNameAndYear(req movies.SearchTMDBRequest) (movies.MovieDetailResponse, error) {
	ret := _m.Called(req)

	var r0 movies.MovieDetailResponse
	if rf, ok := ret.Get(0).(func(movies.SearchTMDBRequest) movies.MovieDetailResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(movies.MovieDetailResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(movies.SearchTMDBRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTMDBClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewTMDBClient creates a new instance of TMDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTMDBClient(t mockConstructorTestingTNewTMDBClient) *TMDBClient {
	mock := &TMDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
